### ISSUE TITLE
Copr repo has no release for Fedora 30

### ISSUE THREAD

**Issue by ondrejsojka** [oleastre/kitty#2]
dnf reports `Failed to synchronize cache for repo 'oleastre-kitty-terminal'` when trying to run dnf upgrade after upgrading to Fedora 30.

Thanks for it so far!

**Comment by oleastre** [comment]
I did not manage to switch to fedora 30 yet and did not enabled copr builds for it. 
I just launched a rebuild with Fedora 30 activated, and it should now be available.
Can you tell me if it's  working for you ?

**Comment by ondrejsojka** [comment]
Successfully updated! Thanks!
