### ISSUE TITLE
Kitty 0.15 broke primary selection

### ISSUE THREAD

**Issue by Fale** [oleastre/kitty#3]
Hi, thanks for the great work!

Updating from kitty-0.14.6-1.fc30.x86_64 to kitty-0.15.0-1.fc30, the primary selection stopped working (both for copying and pasting). Downgrading this single package it started to work again!

**Comment by oleastre** [comment]
I don't really understand what is the issue and I never released 0.15.0 on copr (I almost switched back to gnome-terminal since there are issues between kitty and ssh remote connections)

**Comment by Fale** [comment]
Thanks. Checking better, I noticed that the update arrived from the `updates` repo, so I filled a bugzilla bug: https://bugzilla.redhat.com/show_bug.cgi?id=1787287
